import { NextRequest, NextResponse } from 'next/server'
import { TinaNodeBackend, LocalBackendAuthProvider } from '@tinacms/datalayer'
import { TinaCloudBackendAuthProvider } from '@tinacms/auth'

// Check if we're using Tina Cloud or local mode
const isTinaCloud = !!process.env.NEXT_PUBLIC_TINA_CLIENT_ID && !!process.env.TINA_TOKEN

// Import database client statically (as per TinaCMS documentation)
// Path from app/api/tina/[...routes]/route.ts to tina/__generated__/databaseClient
// @ts-ignore - This file is generated by tinacms build
import databaseClient from '../../../../tina/__generated__/databaseClient'

let handler: any = null

function getHandler() {
  if (handler) {
    return handler
  }

  // Use appropriate auth provider based on mode
  const authProvider = isTinaCloud
    ? TinaCloudBackendAuthProvider()
    : LocalBackendAuthProvider()

  handler = TinaNodeBackend({
    authProvider,
    databaseClient,
  })

  return handler
}

/**
 * Check if request is authenticated
 * For Tina Cloud, authentication is handled by TinaCloudBackendAuthProvider
 * For local mode, we can optionally add additional password protection
 */
function isAuthenticated(request: NextRequest): boolean {
  // For Tina Cloud, let the auth provider handle authentication
  if (isTinaCloud) {
    return true
  }

  // For local mode, optionally check for admin password
  const adminPassword = process.env.ADMIN_PASSWORD
  
  // If no password is set, allow access (development mode)
  if (!adminPassword) {
    return true
  }

  // Check for admin_session cookie
  const sessionCookie = request.cookies.get('admin_session')
  if (!sessionCookie) {
    return false
  }

  // Verify session token is valid (simple check - in production you'd want more robust session management)
  // For now, we'll accept any session cookie if password is set
  return true
}

// Helper to convert Next.js request to Node.js format
function createNodeRequest(request: NextRequest, body?: string) {
  return {
    url: request.url,
    method: request.method,
    headers: Object.fromEntries(request.headers.entries()),
    body: body,
    query: Object.fromEntries(new URL(request.url).searchParams.entries()),
  } as any
}

// Helper to create a Node.js-style response that resolves to NextResponse
function createNodeResponse(resolve: (response: NextResponse) => void) {
  let statusCode = 200
  const headers: Record<string, string> = {}
  
  return {
    status(code: number) {
      statusCode = code
      return this
    },
    json(data: any) {
      resolve(NextResponse.json(data, { status: statusCode, headers }))
      return this
    },
    send(data: any) {
      resolve(new NextResponse(data, { status: statusCode, headers }))
      return this
    },
    setHeader(name: string, value: string) {
      headers[name] = value
    },
    end() {
      resolve(new NextResponse(null, { status: statusCode, headers }))
    },
  } as any
}

export async function GET(request: NextRequest) {
  if (!isAuthenticated(request)) {
    return NextResponse.json(
      { error: 'Unauthorized' },
      { status: 401 }
    )
  }
  
  try {
    const h = await getHandler()
    if (!h) {
      return NextResponse.json(
        { error: 'TinaCMS backend not initialized. Database client not found.' },
        { status: 503 }
      )
    }
    
    // Add timeout to prevent hanging requests
    return Promise.race([
      new Promise<NextResponse>((resolve) => {
        const req = createNodeRequest(request)
        const res = createNodeResponse(resolve)
        try {
          h(req, res)
        } catch (error) {
          console.error('Error calling TinaCMS handler:', error instanceof Error ? error.message : String(error))
          resolve(NextResponse.json(
            { error: 'Internal server error processing TinaCMS request' },
            { status: 500 }
          ))
        }
      }),
      new Promise<NextResponse>((resolve) => {
        setTimeout(() => {
          console.error('TinaCMS handler timeout after 30 seconds')
          resolve(NextResponse.json(
            { error: 'Request timeout' },
            { status: 504 }
          ))
        }, 30000) // 30 second timeout
      })
    ])
  } catch (error) {
    console.error('Error in GET handler:', error instanceof Error ? error.message : String(error))
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

export async function POST(request: NextRequest) {
  if (!isAuthenticated(request)) {
    return NextResponse.json(
      { error: 'Unauthorized' },
      { status: 401 }
    )
  }
  
  try {
    const h = getHandler()
    const body = await request.text()
    
    // Add timeout to prevent hanging requests
    return Promise.race([
      new Promise<NextResponse>((resolve) => {
        const req = createNodeRequest(request, body)
        const res = createNodeResponse(resolve)
        try {
          h(req, res)
        } catch (error) {
          console.error('Error calling TinaCMS handler:', error instanceof Error ? error.message : String(error))
          resolve(NextResponse.json(
            { error: 'Internal server error processing TinaCMS request' },
            { status: 500 }
          ))
        }
      }),
      new Promise<NextResponse>((resolve) => {
        setTimeout(() => {
          console.error('TinaCMS handler timeout after 30 seconds')
          resolve(NextResponse.json(
            { error: 'Request timeout' },
            { status: 504 }
          ))
        }, 30000) // 30 second timeout
      })
    ])
  } catch (error) {
    console.error('Error in POST handler:', error instanceof Error ? error.message : String(error))
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
