import { NextRequest, NextResponse } from 'next/server'
import { TinaNodeBackend, LocalBackendAuthProvider } from '@tinacms/datalayer'
import { TinaCloudBackendAuthProvider } from '@tinacms/auth'

// Check if we're using Tina Cloud or local mode
// Use TINA_PUBLIC_IS_LOCAL if set, otherwise check for Cloud credentials
const isLocal = process.env.TINA_PUBLIC_IS_LOCAL === 'true'
const isTinaCloud = !isLocal && !!process.env.NEXT_PUBLIC_TINA_CLIENT_ID && !!process.env.TINA_TOKEN

// Import database client statically (as per TinaCMS documentation)
// Path from app/api/tina/[[...routes]]/route.ts to tina/__generated__/databaseClient
// @ts-ignore - This file is generated by tinacms build
import databaseClient from '../../../../tina/__generated__/databaseClient'

let handler: any = null

function getHandler() {
  if (handler) {
    return handler
  }

  try {
    // Verify database client is available
    if (!databaseClient) {
      const errorMsg = 'Database client is not available. Make sure tinacms build ran successfully and tina/__generated__/databaseClient.ts exists.'
      console.error(errorMsg)
      throw new Error(errorMsg)
    }

    // Use appropriate auth provider based on mode
    const authProvider = isTinaCloud
      ? TinaCloudBackendAuthProvider()
      : LocalBackendAuthProvider()

    handler = TinaNodeBackend({
      authProvider,
      databaseClient,
    })

    return handler
  } catch (error) {
    console.error('Error initializing TinaCMS handler:', error instanceof Error ? error.message : String(error))
    if (error instanceof Error) {
      console.error('Stack:', error.stack)
    }
    throw error
  }
}

/**
 * Check if request is authenticated
 * For Tina Cloud, authentication is handled by TinaCloudBackendAuthProvider
 * For local mode, we can optionally add additional password protection
 */
function isAuthenticated(request: NextRequest): boolean {
  // For Tina Cloud, let the auth provider handle authentication
  if (isTinaCloud) {
    return true
  }

  // For local mode, optionally check for admin password
  const adminPassword = process.env.ADMIN_PASSWORD
  
  // If no password is set, allow access (development mode)
  if (!adminPassword) {
    return true
  }

  // Check for admin_session cookie
  const sessionCookie = request.cookies.get('admin_session')
  if (!sessionCookie) {
    return false
  }

  // Verify session token is valid (simple check - in production you'd want more robust session management)
  // For now, we'll accept any session cookie if password is set
  return true
}

/**
 * Convert Next.js Request to Node.js-style request object
 * TinaNodeBackend expects Node.js-style req/res objects
 */
function createNodeRequest(request: NextRequest, body?: string, overrideUrl?: string): any {
  const url = new URL(overrideUrl || request.url)
  
  // Create a Node.js-style request object
  const nodeReq: any = {
    url: overrideUrl || request.url,
    method: request.method,
    headers: Object.fromEntries(request.headers.entries()),
    query: Object.fromEntries(url.searchParams.entries()),
    // Add pathname for route matching
    pathname: url.pathname,
  }

  // Add body for POST requests
  if (body !== undefined) {
    nodeReq.body = body
  }

  // Add common Node.js request properties that might be expected
  nodeReq.get = (name: string) => request.headers.get(name)
  nodeReq.header = (name: string) => request.headers.get(name)
  
  return nodeReq
}

/**
 * Create a Node.js-style response object
 * Must support write() method for streaming responses (required by TinaNodeBackend)
 */
function createNodeResponse(resolve: (response: NextResponse) => void): any {
  let statusCode = 200
  const headers: Record<string, string> = {}
  let resolved = false
  const chunks: (string | Buffer)[] = []
  let headersSent = false

  const nodeRes: any = {
    statusCode: 200,
    status(code: number) {
      statusCode = code
      nodeRes.statusCode = code
      return nodeRes
    },
    writeHead(status: number, statusMessage?: string, responseHeaders?: Record<string, string>) {
      if (!headersSent) {
        statusCode = status
        nodeRes.statusCode = status
        if (responseHeaders) {
          Object.entries(responseHeaders).forEach(([key, value]) => {
            headers[key.toLowerCase()] = Array.isArray(value) ? value[0] : value
          })
        }
        headersSent = true
      }
      return nodeRes
    },
    write(chunk: string | Buffer, encoding?: BufferEncoding): boolean {
      // Buffer chunks until end() is called
      // Return true to indicate write was successful
      if (!resolved) {
        chunks.push(chunk)
        if (process.env.NODE_ENV === 'development') {
          console.log('[TinaCMS] write() called, chunk length:', typeof chunk === 'string' ? chunk.length : chunk.length)
        }
        return true
      }
      return false
    },
    json(data: any) {
      if (!resolved) {
        resolved = true
        headers['content-type'] = 'application/json'
        resolve(NextResponse.json(data, { status: statusCode, headers }))
      }
      return nodeRes
    },
    send(data: any) {
      if (!resolved) {
        resolved = true
        const contentType = headers['content-type'] || 'text/plain'
        resolve(new NextResponse(data, { 
          status: statusCode, 
          headers: { ...headers, 'content-type': contentType }
        }))
      }
      return nodeRes
    },
    setHeader(name: string, value: string | string[]) {
      headers[name.toLowerCase()] = Array.isArray(value) ? value[0] : value
      return nodeRes
    },
    getHeader(name: string) {
      return headers[name.toLowerCase()]
    },
    removeHeader(name: string) {
      delete headers[name.toLowerCase()]
      return nodeRes
    },
    getHeaders() {
      return { ...headers }
    },
    hasHeader(name: string) {
      return name.toLowerCase() in headers
    },
    end(data?: string | Buffer, encoding?: BufferEncoding, cb?: () => void) {
      if (!resolved) {
        resolved = true
        // Combine all chunks if write() was used
        let body: string | Buffer | null = null
        
        // If data is provided, add it to chunks
        if (data) {
          chunks.push(data)
        }
        
        // Convert chunks to string if any exist
        let finalBody: string
        if (chunks.length > 0) {
          if (chunks.length === 1) {
            const chunk = chunks[0]
            finalBody = typeof chunk === 'string' ? chunk : chunk.toString(encoding || 'utf8')
          } else {
            finalBody = chunks.map(chunk => 
              typeof chunk === 'string' ? chunk : chunk.toString(encoding || 'utf8')
            ).join('')
          }
        } else if (data) {
          // Data provided directly to end() without write() calls
          finalBody = typeof data === 'string' ? data : data.toString(encoding || 'utf8')
        } else {
          // No chunks and no data - this shouldn't happen for GraphQL queries
          // Log warning and return error response
          console.warn('TinaCMS handler called end() without data or chunks - this may indicate an error')
          finalBody = JSON.stringify({ 
            errors: [{ 
              message: 'Empty response from handler',
              extensions: { code: 'INTERNAL_SERVER_ERROR' }
            }]
          })
        }
        
        // Determine content type - always use application/json for GraphQL
        const contentType = headers['content-type'] || 'application/json'
        
        // Ensure content-type header is set
        const finalHeaders = { ...headers, 'content-type': contentType }
        
        // Log response in development for debugging
        if (process.env.NODE_ENV === 'development') {
          console.log('[TinaCMS] Sending response:', {
            status: statusCode,
            contentType,
            bodyLength: finalBody.length,
            hasData: finalBody.length > 2 && finalBody !== '{}'
          })
        }
        
        resolve(new NextResponse(finalBody, { 
          status: statusCode, 
          headers: finalHeaders
        }))
        
        // Call callback if provided
        if (cb) {
          cb()
        }
      }
      return nodeRes
    },
    // Event emitter methods (may be expected)
    on(event: string, listener: (...args: any[]) => void) {
      // No-op for now, but handler might expect this
      return nodeRes
    },
    once(event: string, listener: (...args: any[]) => void) {
      // No-op for now
      return nodeRes
    },
    emit(event: string, ...args: any[]) {
      // No-op for now
      return false
    },
  }

  return nodeRes
}

/**
 * Handle Tina CMS request
 */
async function handleRequest(
  request: NextRequest,
  params?: { routes?: string[] }
): Promise<NextResponse> {
  try {
    const h = getHandler()
    
    // Get request body for POST requests
    let body: string | undefined
    if (request.method === 'POST' || request.method === 'PUT' || request.method === 'PATCH') {
      try {
        body = await request.text()
      } catch (error) {
        console.error('Error reading request body:', error)
        body = ''
      }
    }
    
    // Build the full URL path including route segments
    // TinaNodeBackend might need the full path including sub-routes
    let requestUrl = request.url
    if (params?.routes && params.routes.length > 0) {
      const url = new URL(request.url)
      // Ensure the path includes the route segments
      const basePath = '/api/tina'
      const routePath = params.routes.join('/')
      url.pathname = `${basePath}/${routePath}`
      requestUrl = url.toString()
    }
    
    // Create Node.js-style request and response objects
    const nodeReq = createNodeRequest(request, body, requestUrl)
    
    return new Promise<NextResponse>((resolve, reject) => {
      let handlerResolved = false
      let timeout: NodeJS.Timeout | null = null
      
      // Wrapper to ensure timeout is cleared when response is sent
      const wrappedResolve = (response: NextResponse) => {
        if (!handlerResolved) {
          handlerResolved = true
          if (timeout) {
            clearTimeout(timeout)
          }
          resolve(response)
        }
      }
      
      const nodeRes = createNodeResponse(wrappedResolve)
      
      // Set a timeout to prevent hanging requests
      timeout = setTimeout(() => {
        if (!handlerResolved) {
          handlerResolved = true
          console.error('TinaCMS handler timeout after 30 seconds')
          wrappedResolve(NextResponse.json(
            { error: 'Request timeout' },
            { status: 504 }
          ))
        }
      }, 30000)
      
      try {
        // Log request in development
        if (process.env.NODE_ENV === 'development') {
          console.log('[TinaCMS] Handling request:', {
            method: nodeReq.method,
            url: nodeReq.url,
            pathname: nodeReq.pathname,
            hasBody: !!body,
            bodyLength: body?.length || 0
          })
        }
        
        // Call the Tina handler
        // TinaNodeBackend may return a promise or use callbacks via nodeRes
        const result = h(nodeReq, nodeRes)
        
        // Handle promise if handler returns one
        if (result && typeof result.then === 'function') {
          result
            .then((response: any) => {
              // Handler promise resolved
              // Response should have been sent via nodeRes methods (write/end)
              // If not resolved after a short delay, something went wrong
              setTimeout(() => {
                if (!handlerResolved) {
                  handlerResolved = true
                  if (timeout) {
                    clearTimeout(timeout)
                  }
                  console.error('[TinaCMS] Handler promise resolved but no response was sent via nodeRes methods')
                  // This shouldn't happen - handler should call end() or json()
                  wrappedResolve(NextResponse.json(
                    { 
                      errors: [{ 
                        message: 'Handler did not send a response',
                        extensions: { code: 'INTERNAL_SERVER_ERROR' }
                      }]
                    },
                    { status: 500 }
                  ))
                }
              }, 100)
            })
            .catch((err: any) => {
              if (!handlerResolved) {
                handlerResolved = true
                if (timeout) {
                  clearTimeout(timeout)
                }
                console.error('[TinaCMS] Handler promise rejected:', err)
                wrappedResolve(NextResponse.json(
                  { 
                    errors: [{ 
                      message: err instanceof Error ? err.message : String(err),
                      extensions: { code: 'INTERNAL_SERVER_ERROR' }
                    }]
                  },
                  { status: 500 }
                ))
              }
            })
        }
        // If handler doesn't return a promise, it uses callbacks (nodeRes methods)
        // The nodeRes methods (write/end/json) will handle sending the response
      } catch (error) {
        if (!handlerResolved) {
          handlerResolved = true
          if (timeout) {
            clearTimeout(timeout)
          }
          console.error('Error calling TinaCMS handler:', error instanceof Error ? error.message : String(error))
          if (error instanceof Error) {
            console.error('Stack:', error.stack)
          }
          wrappedResolve(NextResponse.json(
            { 
              error: 'Internal server error', 
              message: error instanceof Error ? error.message : String(error)
            },
            { status: 500 }
          ))
        }
      }
    })
  } catch (error) {
    console.error('Error in handleRequest:', error instanceof Error ? error.message : String(error))
    throw error
  }
}

export async function GET(
  request: NextRequest,
  { params }: { params: { routes?: string[] } }
) {
  if (!isAuthenticated(request)) {
    return NextResponse.json(
      { error: 'Unauthorized' },
      { status: 401 }
    )
  }
  
  try {
    return await handleRequest(request, params)
  } catch (error) {
    console.error('Error in GET handler:', error instanceof Error ? error.message : String(error))
    if (error instanceof Error) {
      console.error('Stack:', error.stack)
    }
    return NextResponse.json(
      { 
        error: 'Internal server error', 
        message: error instanceof Error ? error.message : String(error),
        // Include helpful error message for database client issues
        hint: error instanceof Error && error.message.includes('database client') 
          ? 'Make sure tinacms build ran successfully before deployment'
          : undefined
      },
      { status: 500 }
    )
  }
}

export async function POST(
  request: NextRequest,
  { params }: { params: { routes?: string[] } }
) {
  if (!isAuthenticated(request)) {
    return NextResponse.json(
      { error: 'Unauthorized' },
      { status: 401 }
    )
  }
  
  try {
    return await handleRequest(request, params)
  } catch (error) {
    console.error('Error in POST handler:', error instanceof Error ? error.message : String(error))
    if (error instanceof Error) {
      console.error('Stack:', error.stack)
    }
    return NextResponse.json(
      { 
        error: 'Internal server error', 
        message: error instanceof Error ? error.message : String(error),
        // Include helpful error message for database client issues
        hint: error instanceof Error && error.message.includes('database client') 
          ? 'Make sure tinacms build ran successfully before deployment'
          : undefined
      },
      { status: 500 }
    )
  }
}
