import { NextRequest, NextResponse } from 'next/server'
import { TinaNodeBackend, LocalBackendAuthProvider } from '@tinacms/datalayer'
import { TinaCloudBackendAuthProvider } from '@tinacms/auth'

// Check if we're using Tina Cloud or local mode
// Use TINA_PUBLIC_IS_LOCAL if set, otherwise check for Cloud credentials
const isLocal = process.env.TINA_PUBLIC_IS_LOCAL === 'true'
const isTinaCloud = !isLocal && !!process.env.NEXT_PUBLIC_TINA_CLIENT_ID && !!process.env.TINA_TOKEN

// Import database client statically (as per TinaCMS documentation)
// Path from app/api/tina/[[...routes]]/route.ts to tina/__generated__/databaseClient
// @ts-ignore - This file is generated by tinacms build
import databaseClient from '../../../../tina/__generated__/databaseClient'

let handler: any = null

function getHandler() {
  if (handler) {
    return handler
  }

  try {
    // Verify database client is available
    if (!databaseClient) {
      const errorMsg = 'Database client is not available. Make sure tinacms build ran successfully and tina/__generated__/databaseClient.ts exists.'
      console.error(errorMsg)
      throw new Error(errorMsg)
    }

    // Use appropriate auth provider based on mode
    const authProvider = isTinaCloud
      ? TinaCloudBackendAuthProvider()
      : LocalBackendAuthProvider()

    handler = TinaNodeBackend({
      authProvider,
      databaseClient,
    })

    return handler
  } catch (error) {
    console.error('Error initializing TinaCMS handler:', error instanceof Error ? error.message : String(error))
    if (error instanceof Error) {
      console.error('Stack:', error.stack)
    }
    throw error
  }
}

/**
 * Check if request is authenticated
 * For Tina Cloud, authentication is handled by TinaCloudBackendAuthProvider
 * For local mode, we can optionally add additional password protection
 */
function isAuthenticated(request: NextRequest): boolean {
  // For Tina Cloud, let the auth provider handle authentication
  if (isTinaCloud) {
    return true
  }

  // For local mode, optionally check for admin password
  const adminPassword = process.env.ADMIN_PASSWORD
  
  // If no password is set, allow access (development mode)
  if (!adminPassword) {
    return true
  }

  // Check for admin_session cookie
  const sessionCookie = request.cookies.get('admin_session')
  if (!sessionCookie) {
    return false
  }

  // Verify session token is valid (simple check - in production you'd want more robust session management)
  // For now, we'll accept any session cookie if password is set
  return true
}

/**
 * Convert Next.js Request to Node.js-style request object
 * TinaNodeBackend expects Node.js-style req/res objects
 */
function createNodeRequest(request: NextRequest, body?: string): any {
  const url = new URL(request.url)
  
  // Create a Node.js-style request object
  const nodeReq: any = {
    url: request.url,
    method: request.method,
    headers: Object.fromEntries(request.headers.entries()),
    query: Object.fromEntries(url.searchParams.entries()),
  }

  // Add body for POST requests
  if (body !== undefined) {
    nodeReq.body = body
  }

  // Add common Node.js request properties that might be expected
  nodeReq.get = (name: string) => request.headers.get(name)
  nodeReq.header = (name: string) => request.headers.get(name)
  
  return nodeReq
}

/**
 * Create a Node.js-style response object
 */
function createNodeResponse(resolve: (response: NextResponse) => void): any {
  let statusCode = 200
  const headers: Record<string, string> = {}
  let resolved = false

  const nodeRes: any = {
    status(code: number) {
      statusCode = code
      return nodeRes
    },
    json(data: any) {
      if (!resolved) {
        resolved = true
        resolve(NextResponse.json(data, { status: statusCode, headers }))
      }
      return nodeRes
    },
    send(data: any) {
      if (!resolved) {
        resolved = true
        const contentType = headers['content-type'] || 'text/plain'
        resolve(new NextResponse(data, { 
          status: statusCode, 
          headers: { ...headers, 'content-type': contentType }
        }))
      }
      return nodeRes
    },
    setHeader(name: string, value: string) {
      headers[name.toLowerCase()] = value
      return nodeRes
    },
    getHeader(name: string) {
      return headers[name.toLowerCase()]
    },
    end(data?: any) {
      if (!resolved) {
        resolved = true
        if (data) {
          resolve(new NextResponse(data, { status: statusCode, headers }))
        } else {
          resolve(new NextResponse(null, { status: statusCode, headers }))
        }
      }
      return nodeRes
    },
  }

  return nodeRes
}

/**
 * Handle Tina CMS request
 */
async function handleRequest(request: NextRequest): Promise<NextResponse> {
  try {
    const h = getHandler()
    
    // Get request body for POST requests
    let body: string | undefined
    if (request.method === 'POST' || request.method === 'PUT' || request.method === 'PATCH') {
      try {
        body = await request.text()
      } catch (error) {
        console.error('Error reading request body:', error)
        body = ''
      }
    }
    
    // Create Node.js-style request and response objects
    const nodeReq = createNodeRequest(request, body)
    
    return new Promise<NextResponse>((resolve, reject) => {
      const nodeRes = createNodeResponse(resolve)
      let handlerResolved = false
      
      // Set a timeout to prevent hanging requests
      const timeout = setTimeout(() => {
        if (!handlerResolved) {
          handlerResolved = true
          console.error('TinaCMS handler timeout after 30 seconds')
          resolve(NextResponse.json(
            { error: 'Request timeout' },
            { status: 504 }
          ))
        }
      }, 30000)
      
      try {
        // Call the Tina handler
        const result = h(nodeReq, nodeRes)
        
        // Handle promise if handler returns one
        if (result && typeof result.then === 'function') {
          result
            .then(() => {
              if (!handlerResolved) {
                handlerResolved = true
                clearTimeout(timeout)
                // Handler should have called nodeRes methods, but if not, send empty response
                if (!nodeRes._resolved) {
                  resolve(new NextResponse(null, { status: 200 }))
                }
              }
            })
            .catch((err: any) => {
              if (!handlerResolved) {
                handlerResolved = true
                clearTimeout(timeout)
                console.error('TinaCMS handler promise rejected:', err)
                reject(err)
              }
            })
        } else {
          // Handler is synchronous or uses callbacks
          // Clear timeout if handler resolves quickly
          // The nodeRes methods will handle the response
        }
      } catch (error) {
        if (!handlerResolved) {
          handlerResolved = true
          clearTimeout(timeout)
          console.error('Error calling TinaCMS handler:', error instanceof Error ? error.message : String(error))
          if (error instanceof Error) {
            console.error('Stack:', error.stack)
          }
          reject(error)
        }
      }
    })
  } catch (error) {
    console.error('Error in handleRequest:', error instanceof Error ? error.message : String(error))
    throw error
  }
}

export async function GET(request: NextRequest) {
  if (!isAuthenticated(request)) {
    return NextResponse.json(
      { error: 'Unauthorized' },
      { status: 401 }
    )
  }
  
  try {
    return await handleRequest(request)
  } catch (error) {
    console.error('Error in GET handler:', error instanceof Error ? error.message : String(error))
    if (error instanceof Error) {
      console.error('Stack:', error.stack)
    }
    return NextResponse.json(
      { 
        error: 'Internal server error', 
        message: error instanceof Error ? error.message : String(error),
        // Include helpful error message for database client issues
        hint: error instanceof Error && error.message.includes('database client') 
          ? 'Make sure tinacms build ran successfully before deployment'
          : undefined
      },
      { status: 500 }
    )
  }
}

export async function POST(request: NextRequest) {
  if (!isAuthenticated(request)) {
    return NextResponse.json(
      { error: 'Unauthorized' },
      { status: 401 }
    )
  }
  
  try {
    return await handleRequest(request)
  } catch (error) {
    console.error('Error in POST handler:', error instanceof Error ? error.message : String(error))
    if (error instanceof Error) {
      console.error('Stack:', error.stack)
    }
    return NextResponse.json(
      { 
        error: 'Internal server error', 
        message: error instanceof Error ? error.message : String(error),
        // Include helpful error message for database client issues
        hint: error instanceof Error && error.message.includes('database client') 
          ? 'Make sure tinacms build ran successfully before deployment'
          : undefined
      },
      { status: 500 }
    )
  }
}
