import { NextRequest, NextResponse } from 'next/server'
import { TinaNodeBackend, LocalBackendAuthProvider } from '@tinacms/datalayer'
import { TinaCloudBackendAuthProvider } from '@tinacms/auth'

// Check if we're using Tina Cloud or local mode
const isTinaCloud = !!process.env.NEXT_PUBLIC_TINA_CLIENT_ID && !!process.env.TINA_TOKEN

// Import database client statically (as per TinaCMS documentation)
// Path from app/api/tina/[[...routes]]/route.ts to tina/__generated__/databaseClient
// @ts-ignore - This file is generated by tinacms build
import databaseClient from '../../../../tina/__generated__/databaseClient'

let handler: any = null

function getHandler() {
  if (handler) {
    return handler
  }

  try {
    // Verify database client is available
    if (!databaseClient) {
      throw new Error('Database client is not available. Make sure tinacms build ran successfully.')
    }

    // Use appropriate auth provider based on mode
    const authProvider = isTinaCloud
      ? TinaCloudBackendAuthProvider()
      : LocalBackendAuthProvider()

    handler = TinaNodeBackend({
      authProvider,
      databaseClient,
    })

    return handler
  } catch (error) {
    console.error('Error initializing TinaCMS handler:', error instanceof Error ? error.message : String(error))
    if (error instanceof Error) {
      console.error('Stack:', error.stack)
    }
    throw error
  }
}

/**
 * Check if request is authenticated
 * For Tina Cloud, authentication is handled by TinaCloudBackendAuthProvider
 * For local mode, we can optionally add additional password protection
 */
function isAuthenticated(request: NextRequest): boolean {
  // For Tina Cloud, let the auth provider handle authentication
  if (isTinaCloud) {
    return true
  }

  // For local mode, optionally check for admin password
  const adminPassword = process.env.ADMIN_PASSWORD
  
  // If no password is set, allow access (development mode)
  if (!adminPassword) {
    return true
  }

  // Check for admin_session cookie
  const sessionCookie = request.cookies.get('admin_session')
  if (!sessionCookie) {
    return false
  }

  // Verify session token is valid (simple check - in production you'd want more robust session management)
  // For now, we'll accept any session cookie if password is set
  return true
}

/**
 * Convert Next.js request to Node.js-style request and handle response
 */
async function handleRequest(request: NextRequest): Promise<NextResponse> {
  const h = getHandler()
  
  // Convert Next.js request to Node.js-style request
  const url = new URL(request.url)
  const body = request.method === 'POST' ? await request.text() : undefined
  
  const nodeReq = {
    url: request.url,
    method: request.method,
    headers: Object.fromEntries(request.headers.entries()),
    body: body,
    query: Object.fromEntries(url.searchParams.entries()),
  } as any
  
  return new Promise<NextResponse>((resolve, reject) => {
    let statusCode = 200
    const headers: Record<string, string> = {}
    let resolved = false
    
    const nodeRes = {
      status(code: number) {
        statusCode = code
        return nodeRes
      },
      json(data: any) {
        if (!resolved) {
          resolved = true
          resolve(NextResponse.json(data, { status: statusCode, headers }))
        }
        return nodeRes
      },
      send(data: any) {
        if (!resolved) {
          resolved = true
          resolve(new NextResponse(data, { status: statusCode, headers }))
        }
        return nodeRes
      },
      setHeader(name: string, value: string) {
        headers[name] = value
        return nodeRes
      },
      end() {
        if (!resolved) {
          resolved = true
          resolve(new NextResponse(null, { status: statusCode, headers }))
        }
        return nodeRes
      },
    } as any
    
    try {
      const result = h(nodeReq, nodeRes)
      if (result && typeof result.then === 'function') {
        result.then(() => {
          // Handler resolved via nodeRes methods
          if (!resolved) {
            resolved = true
            resolve(new NextResponse(null, { status: statusCode, headers }))
          }
        }).catch((err: any) => {
          if (!resolved) {
            resolved = true
            console.error('Handler promise rejected:', err)
            reject(err)
          }
        })
      }
      
      // Timeout fallback - if handler doesn't respond within 5 seconds
      setTimeout(() => {
        if (!resolved) {
          resolved = true
          console.error('Handler timeout - no response received')
          resolve(NextResponse.json(
            { error: 'Request timeout' },
            { status: 504 }
          ))
        }
      }, 5000)
    } catch (error) {
      if (!resolved) {
        resolved = true
        console.error('Error calling handler:', error instanceof Error ? error.message : String(error))
        if (error instanceof Error) {
          console.error('Stack:', error.stack)
        }
        reject(error)
      }
    }
  })
}

export async function GET(request: NextRequest) {
  if (!isAuthenticated(request)) {
    return NextResponse.json(
      { error: 'Unauthorized' },
      { status: 401 }
    )
  }
  
  try {
    return await handleRequest(request)
  } catch (error) {
    console.error('Error in GET handler:', error instanceof Error ? error.message : String(error))
    if (error instanceof Error) {
      console.error('Stack:', error.stack)
    }
    return NextResponse.json(
      { error: 'Internal server error', details: error instanceof Error ? error.message : String(error) },
      { status: 500 }
    )
  }
}

export async function POST(request: NextRequest) {
  if (!isAuthenticated(request)) {
    return NextResponse.json(
      { error: 'Unauthorized' },
      { status: 401 }
    )
  }
  
  try {
    return await handleRequest(request)
  } catch (error) {
    console.error('Error in POST handler:', error instanceof Error ? error.message : String(error))
    if (error instanceof Error) {
      console.error('Stack:', error.stack)
    }
    return NextResponse.json(
      { error: 'Internal server error', details: error instanceof Error ? error.message : String(error) },
      { status: 500 }
    )
  }
}
